Repository juliendargelos/street-of-age, pull requests merged in 2019-05, with the labels that each got.

#7 [FIX] - Game scale
  sources/client/src/components/RoomGame.vue
  sources/client/src/components/VirtualJoystick.vue
Labels: dev, fix

#8 [FEAT] - Support atlas in SVGMapper
  scripts/svgmapper/@types/index.d.ts
  scripts/svgmapper/index.ts
  scripts/svgmapper/parser.ts
  sources/client/atlases/level/buildings/Batiment1.png
  sources/client/atlases/level/buildings/Batiment2.png
  sources/client/atlases/level/buildings/Batiment3.png
  sources/client/atlases/level/props/Lampadaire-.png
  sources/client/atlases/level/props/Poubelle.png
  sources/client/public/atlases/level.json
  sources/client/public/atlases/level.png
  sources/client/public/atlases/main.json
  sources/client/public/atlases/main.png
  sources/client/public/pack.json
  sources/client/vue.config.js
  sources/shared/@types/index.d.ts
Labels: dev, feature

#9 [REFACTO] Server shared API
  scripts/svgmapper/index.ts
  scripts/svgmapper/parser.ts
  sources/server/index.ts
  sources/server/src/@types/index.d.ts
  sources/server/src/Server.ts
  sources/server/src/browser.js
  sources/server/src/entities/Player.ts
  sources/server/src/entities/Room.ts
  sources/server/src/game/Character.ts
  sources/server/src/game/Game.ts
  sources/server/src/handlers/SocketPlayer.ts
  sources/server/src/handlers/SocketRoom.ts
  sources/server/src/managers/PlayerManager.ts
  sources/server/src/managers/RoomManager.ts
  sources/server/tsconfig.json
  sources/server/yarn.lock
  sources/shared/.gitignore
  sources/shared/game/character.ts
  sources/shared/game/events.ts
  sources/shared/game/game.ts
  sources/shared/game/index.ts
  sources/shared/package.json
  sources/shared/src/@types/index.d.ts
  sources/shared/src/@types/level.d.ts
  sources/shared/src/@types/serializable.d.ts
  sources/shared/src/@types/sprite.d.ts
  sources/shared/src/entities/player.ts
  sources/shared/src/entities/room.ts
  sources/shared/src/game/character.ts
  sources/shared/src/game/game.ts
  sources/shared/src/socket/events.ts
  sources/shared/tsconfig.json
  sources/shared/yarn.lock
Labels: dev

#10 [FIX] - SVGMapper export
  scripts/svgmapper/parser.ts
  sources/shared/src/@types/level.d.ts
  sources/shared/src/@types/sprite.d.ts
Labels: dev, feature, fix

#19 [FEAT] - Parallax
  scripts/svgmapper/parser.ts
  scripts/svgmapper/sources/Street.svg
  scripts/svgmapper/template.sketch
  scripts/svgmapper/tsconfig.json
  sources/client/atlases/level/backgrounds/buildings_group.png
  sources/client/atlases/level/buildings/Batiment1.png
  sources/client/atlases/level/buildings/Batiment2.png
  sources/client/atlases/level/buildings/building_1.png
  sources/client/atlases/level/buildings/building_2.png
  sources/client/atlases/level/buildings/building_3.png
  sources/client/atlases/level/buildings/building_4.png
  sources/client/atlases/level/buildings/building_5.png
  sources/client/atlases/level/buildings/building_6.png
  sources/client/atlases/level/buildings/building_7.png
  sources/client/atlases/level/buildings/building_8.png
  sources/client/atlases/level/lights/LigthtBatiment1.png
  sources/client/atlases/level/lights/floorlamp.png
  sources/client/atlases/level/props/car.png
  sources/client/atlases/level/props/fire_hydrant.png
  sources/client/atlases/level/props/floorlamp.png
  sources/client/atlases/level/props/forbidden.png
  sources/client/atlases/level/props/stop.png
  sources/client/atlases/level/props/trash.png
  sources/client/public/sprites/levels/Batiment1.png
  sources/client/public/sprites/levels/Lampadaire.png
  sources/client/public/sprites/levels/LightLampadaire.png
  sources/client/public/sprites/levels/LigthtBatiment1.png
  sources/client/src/assets/levels/Street.level.json
  sources/client/src/components/RoomGame.vue
  sources/client/src/constants.ts
  sources/client/src/game/GameLevelBuilder.ts
  sources/client/src/game/entities/Character.ts
  sources/client/src/game/entities/GameLevel.ts
  sources/client/src/game/entities/Projectile.ts
  sources/client/src/game/scenes/GameScene.ts
  sources/shared/.gitignore
  sources/shared/src/@types/index.d.ts
  sources/shared/src/@types/level.d.ts
  sources/shared/src/@types/sprite.d.ts
Labels: dev, fix, svgmapper
