Repository juliendargelos/street-of-age, pull requests merged in 2019-06, with the labels that each got.

#24 [FEAT] Postprocessing
  sources/client/src/game/PostProcessing.ts
  sources/client/src/game/scenes/GameScene.ts
Labels: feature

#26 [CI] - Correct server url for previews instances
  netlify.toml
  sources/client/package.json
  sources/client/scripts/create-env.js
Labels: dev, feature

#29 [FIX] Cast listeners to EventListener
  sources/client/src/game/entities/TouchDetection.ts
  sources/client/src/game/manager/InputManager.ts
Labels: bug

#34 [UI] - Fixes
  sources/client/src/assets/characters/pictures/doting-granny.png
  sources/client/src/assets/characters/pictures/doting-granny_face.png
  sources/client/src/assets/characters/pictures/egocentric.png
  sources/client/src/assets/characters/pictures/egocentric_face.png
  sources/client/src/assets/characters/pictures/fattie.png
  sources/client/src/assets/characters/pictures/fattie_face.png
  sources/client/src/assets/characters/pictures/fusty_grandpa.png
  sources/client/src/assets/characters/pictures/fusty_grandpa_face.png
  sources/client/src/assets/characters/pictures/geek.png
  sources/client/src/assets/characters/pictures/geek_face.png
  sources/client/src/assets/characters/pictures/hippie.png
  sources/client/src/assets/characters/pictures/hippie_face.png
  sources/client/src/assets/characters/pictures/lapdog_woman.png
  sources/client/src/assets/characters/pictures/lapdog_woman_face.png
  sources/client/src/assets/characters/pictures/mr_muscle.png
  sources/client/src/assets/characters/pictures/mr_muscle_face.png
  sources/client/src/assets/logo.png
  sources/client/src/assets/splashscreen.png
  sources/client/src/components/AppButton.vue
  sources/client/src/components/BackButton.vue
  sources/client/src/components/HomeMenu.vue
  sources/client/src/components/PlayerWaitingCard.vue
  sources/client/src/components/ui/SetupCharacterReadyOverlay.vue
  sources/client/src/stylesheets/transitions.sass
  sources/client/src/views/Home.vue
  sources/client/src/views/RoomFinish.vue
  sources/client/src/views/RoomForm.vue
  sources/client/src/views/RoomList.vue
  sources/client/src/views/RoomSetupCharacter.vue
  sources/client/src/views/RoomWaiting.vue
Labels: fix, ui

#33 [FIX] - Characters colliders boxes
  sources/client/src/assets/characters/index.ts
  sources/client/src/game/entities/Character.ts
  sources/client/src/game/entities/MeleeAttack.ts
Labels: dev, fix

#36 [FEAT] - Sounds
  sources/client/public/pack.json
  sources/client/public/sounds/bg.m4a
  sources/client/public/sounds/bg.mp3
  sources/client/public/sounds/bg.ogg
  sources/client/public/sounds/menu.m4a
  sources/client/public/sounds/menu.mp3
  sources/client/public/sounds/menu.ogg
  sources/client/public/sounds/sfx/button.mp3
  sources/client/public/sounds/sfx/distance.m4a
  sources/client/public/sounds/sfx/distance.mp3
  sources/client/public/sounds/sfx/distance.ogg
  sources/client/public/sounds/sfx/explosion.m4a
  sources/client/public/sounds/sfx/explosion.mp3
  sources/client/public/sounds/sfx/explosion.ogg
  sources/client/public/sounds/sfx/jump.m4a
  sources/client/public/sounds/sfx/jump.mp3
  sources/client/public/sounds/sfx/jump.ogg
  sources/client/public/sounds/sfx/melee.m4a
  sources/client/public/sounds/sfx/melee.mp3
  sources/client/public/sounds/sfx/melee.ogg
  sources/client/public/sounds/sfx/start.m4a
  sources/client/public/sounds/sfx/start.mp3
  sources/client/public/sounds/sfx/start.ogg
  sources/client/src/App.vue
  sources/client/src/components/AppButton.vue
  sources/client/src/components/BackButton.vue
  sources/client/src/components/ui/GameUI.vue
  sources/client/src/game/entities/Character.ts
  sources/client/src/game/entities/MeleeAttack.ts
  sources/client/src/game/entities/Projectile.ts
  sources/client/src/game/manager/AudioManager.ts
  sources/client/src/game/manager/GameManager.ts
  sources/client/src/game/scenes/GameScene.ts
Labels: dev, feature, sounds

#40 [TWEAK] - Character values
  sources/client/src/assets/characters/index.ts
  sources/client/src/components/VirtualJoystick.vue
Labels: dev, fix

#43 [FEAT] Game end
  sources/client/src/views/RoomFinish.vue
  sources/server/src/controllers/GameController.ts
  sources/server/src/controllers/RoomController.ts
  sources/server/src/entities/Game.ts
  sources/server/src/entities/Player.ts
Labels: feature

#46 [FIX] Glitch on mobile
  sources/client/src/game/PostProcessing.ts
Labels: fix
